CREATE DATABASE mi_base;
USE mi_base;
CREATE TABLE usuarios(
id INT NOT NULL UNIQUE AUTO_INCREMENT,
nombre VARCHAR(25) NOT NULL UNIQUE,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
fecha_registro DATETIME NOT NULL,
activo TINYINT NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE entradas(
id INT NOT NULL UNIQUE AUTO_INCREMENT,
id_autor INT NOT NULL,
url VARCHAR(255) NOT NULL UNIQUE,
titulo VARCHAR(255) NOT NULL UNIQUE,
texto TEXT NOT NULL,
fecha DATETIME NOT NULL,
activa TINYINT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id_autor) REFERENCES usuarios (id)
ON UPDATE CASCADE
ON DELETE RESTRICT
);

CREATE TABLE comentarios (
id INT NOT NULL UNIQUE AUTO_INCREMENT,
id_autor INT NOT NULL,
id_entrada INT NOT NULL,
titulo VARCHAR(255) NOT NULL UNIQUE,
texto TEXT NOT NULL,
fecha DATETIME NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id_autor) REFERENCES usuarios (id)
ON UPDATE CASCADE
ON DELETE RESTRICT,
FOREIGN KEY (id_entrada) REFERENCES entradas (id)
ON UPDATE CASCADE
ON DELETE RESTRICT
);